### ISSUE TITLE
There is no sound

### ISSUE THREAD

**Issue by TomaszGasior** [flathub/org.frozen_bubble.frozen-bubble#9]
There is an error in console: "Warning: can't initialize sound (reason: Could not create to PulseAudio stream)". I use Fedora 34 where Pipewire is used as sound server instead PulseAudio.

**Comment by hfiguiere** [comment]
but do you have pipewire-pulse?

**Comment by TomaszGasior** [comment]
My Fedora installation is just default. Other software has not been rewritten to Pipewire, so yep, that should work. I have pipewire-pulse service: it works.

**Comment by TomaszGasior** [comment]
I had to remove configuration file to solve the issue.
